server__ip: 192.168.0.101
audio_path: /home/io/echoes-of-tomorrow/audio_files
voice_path:
  0: /home/io/echoes-of-tomorrow/src_server/voices/nl_BE-rdh-medium.onnx
  1: /home/io/echoes-of-tomorrow/src_server/voices/nl_BE-nathalie-medium.onnx
  2: /home/io/echoes-of-tomorrow/src_server/voices/nl_BE-rdh-medium.onnx
  3: /home/io/echoes-of-tomorrow/src_server/voices/nl_BE-nathalie-medium.onnx
booth_id: 0
unique_port:
  0: 8765
  1: 8766
  2: 8767
  3: 8768
booth_ip:
  0: 192.168.0.101
  1: 192.168.0.102
  2: 192.168.0.103
  3: 192.168.0.104
